travis:
  secure:
    BINSTAR_TOKEN: dBr0h+JBW9B5kB0f4GRQfhP62HLirbQA14SRkbUPdaWk+bjJwV+aQPXv0IDiBK/XdAqWhxb3tR/jxn+UHy+vlFHZD+uBU/aUYc/hl2t26UiK792taZwN6d7dW4RAS6q+IXPzWXV5XuA4wuDPOKuCXhUvg3dBoV24pGUk9fUIQFLivw07cfxlbzpvrDTyv1YiiyNHkAAZEM7HfJZQog7rM6JGxJhQ2Opoov81ELr0SR4J8Le1+4RR3JAfHI3OyVaFqr6qXo1Dz7qb6x3h4J3zM36hw1m+OvcOe0mePUHtd7JWY7gJ51D0u2ahAv/hyKJj+sMUOGrajpC/Ga/1VTTXF4abXzkzYzdJkdeenrxgyDlX231BEkPbpmBYVuYiI7deGpKvQxq4eRbx6cSTosb72tPJb9pGEZ7VbfYX9A0uIMwUXnFllycMZfu5njdFsQvaBgzJL/HzQzEkvFVKJhb7nsajg4HfeeRx43iooaKlWEeZQfRG+7RgbM+FRr2tR67NSvnWHuzg0lVzSrKPHhIwPvfSERLpn/Vtm4ZTWqEo0BF8lokZidXG+ExLNPHJ6JYR6DdXvouzXkhKQbmtTB349H/zcvSDOSmqNbVcJ3cmkERiRzERWpww2LIV6Fw9zkyqyq+Vv41Nf/KHKnSUy5kON+h39HWkoHEhOvc5MCYQbt4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
